### ISSUE TITLE
Ran out of input

### ISSUE THREAD

**Issue by dreamingcp** [chsasank/ATIS.keras#3]
When I execute: `python main.py` ,I got this error:
```
Using TensorFlow backend.
Traceback (most recent call last):
  File "main.py", line 19, in <module>
    train_set, valid_set, dicts = data.load.atisfull()
  File "/home/c1/gitcloned/ATIS.keras/data/load.py", line 51, in atisfull
    train_set, test_set, dicts = pickle.load(f)
EOFError: Ran out of input
```
How can I fix it ?
Please help me, thanks a lot!

**Comment by dreamingcp** [comment]
I find it !
My file `atis.pkl` is empty, because there are some errors during downloading. So I download it manually and it works well.
